"""Tests for polaron_qc.acquisition. Synthetic data for the logic; the real caches / one real image only in the
smoke tests at the bottom (skipped when the data are not present)."""
import os

import numpy as np
import pandas as pd
import pytest
from scipy import stats as sps

from polaron_qc import CRACKED_SITES, GREY_PORE_SITES, LOW_CONTRAST_SITES, PRIMARY_KPIS
from polaron_qc import acquisition as acq

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "analysis_cache")
DATASET = os.path.join(ROOT, "Dataset")


# ----------------------------------------------------------------------------------------------------- helpers
def _sites(batch, names, **cols):
    df = pd.DataFrame(dict(batch=batch, site=list(names)))
    df["bright_low_contrast"] = False
    df["bright_sep"] = 60.0
    df["graphite_mode"] = 55
    df["etd_curtain_frac"] = 0.007
    df["etd_boundary_sharpness"] = 0.9
    df["th_lo"] = 30.0
    df["th_hi"] = 100.0
    for k, v in cols.items():
        df[k] = v
    return df


def _images(sites, bse_p1=0, bse_ebf=0.05, etd_ebf=0.05, il_ebf=0.05, band_top=0, band_bottom=0):
    rows = []
    for i, r in sites.reset_index(drop=True).iterrows():
        pick = lambda v: v[i] if isinstance(v, (list, np.ndarray, pd.Series)) else v
        for det, p1, ebf in (("BSE", pick(bse_p1), pick(bse_ebf)), ("SE", 0, pick(etd_ebf)), ("Inlens", 0, pick(il_ebf))):
            rows.append(dict(batch=r.batch, site=r.site, det=det, H=2300, mean=60.0, p1=p1, p50=58.0, p99=120, std=23.0,
                             gray_levels=150, empty_bin_frac=ebf, band_top=pick(band_top) if det == "BSE" else 0,
                             band_bottom=pick(band_bottom) if det == "BSE" else 0))
    return pd.DataFrame(rows)


def _kpi_frame(batch, n, rng, cov, kpi_fn, blc=False):
    """Site table with the five primary KPIs generated by kpi_fn(cov, rng, j) and one covariate column 'cov'."""
    df = pd.DataFrame(dict(batch=batch, site=[f"{batch}_s{i}" for i in range(n)]))
    df["cov"] = cov
    for j, k in enumerate(PRIMARY_KPIS):
        df[k] = kpi_fn(cov, rng, j)
    df["bright_low_contrast"] = blc
    return df


def _flags_from(df, group="ordinary"):
    return pd.DataFrame(dict(batch=df.batch, site=df.site, acquisition_group=group, cov=df["cov"]))


# ------------------------------------------------------------------------------------------------ derive_flags
def test_derive_flags_precedence_and_sources():
    names = [CRACKED_SITES[0], GREY_PORE_SITES[0], CRACKED_SITES[1], GREY_PORE_SITES[1], "plain"]
    sites = _sites("Batch_3", names, bright_low_contrast=[True, True, False, False, False])
    sites["grey_pore"] = True  # the features column is deliberately ignored; the flag is re-derived from data / list
    images = _images(sites, bse_p1=[0, 0, 20, 0, 0], bse_ebf=[0.5, 0.05, 0.05, 0.05, 0.05], il_ebf=[0.05, 0.3, 0.05, 0.05, 0.05],
                     band_top=[10, 0, 0, 0, 0], band_bottom=[5, 0, 0, 0, 0])
    f = acq.derive_flags(sites, images).set_index("site")
    # precedence low_contrast > grey_pore > cracked > ordinary
    assert f.loc[CRACKED_SITES[0], "acquisition_group"] == "low_contrast"
    assert f.loc[GREY_PORE_SITES[0], "acquisition_group"] == "low_contrast"
    assert f.loc[CRACKED_SITES[1], "acquisition_group"] == "grey_pore"       # raised black level beats the cracked label
    assert f.loc[CRACKED_SITES[1], "grey_pore_source"] == "data"
    assert f.loc[CRACKED_SITES[1], "cracked_known"]
    assert f.loc[GREY_PORE_SITES[1], "acquisition_group"] == "grey_pore"     # list only (p1 = 0)
    assert f.loc[GREY_PORE_SITES[1], "grey_pore_source"] == "list"
    assert f.loc["plain", "acquisition_group"] == "ordinary" and not f.loc["plain", "grey_pore"]
    # the other flags
    assert f.loc[CRACKED_SITES[0], "contrast_stretched_bse"] and f.loc[CRACKED_SITES[0], "contrast_stretched_any"]
    assert not f.loc[GREY_PORE_SITES[0], "contrast_stretched_bse"] and f.loc[GREY_PORE_SITES[0], "contrast_stretched_any"]
    assert f.loc[CRACKED_SITES[0], "band_rows"] == 15
    assert set(f.acquisition_group.unique()) <= set(acq.ACQUISITION_GROUPS)
    for c in acq.ACQ_COVARIATES + ["bse_p50", "etd_p50", "inlens_p50"]:
        assert c in f.columns


def test_derive_flags_unseen_batch_uses_data_only():
    names = ["u1", "u2", "u3", "u4"]
    sites = _sites("Batch_X", names, bright_low_contrast=[False, False, True, False])
    images = _images(sites, bse_p1=[0, 25, 0, 4], bse_ebf=[0.05, 0.0, 0.1, 0.35])
    f = acq.derive_flags(sites, images).set_index("site")
    assert list(f.acquisition_group) == ["ordinary", "grey_pore", "low_contrast", "ordinary"]
    assert not f.cracked_known.any()                      # reference-only label: always False on an unseen batch
    assert f.loc["u2", "grey_pore_source"] == "data"
    assert f.loc["u4", "contrast_stretched_bse"] and f.loc["u4", "acquisition_group"] == "ordinary"
    assert f.loc["u3", "bright_low_contrast_source"] == "data"
    # without a bright_low_contrast column the list is the only source and nothing in it matches an unseen batch
    f2 = acq.derive_flags(sites.drop(columns=["bright_low_contrast"]), images).set_index("site")
    assert not f2.bright_low_contrast.any() and f2.loc["u3", "acquisition_group"] == "ordinary"
    assert (f2.bright_low_contrast_source == "list").all()


# ------------------------------------------------------------------------------------------- stratified view
def test_stratified_refuses_below_four_sites():
    rng = np.random.default_rng(1)
    ref = _kpi_frame("R", 8, rng, rng.normal(size=8), lambda c, r, j: r.normal(1, .1, len(c)))
    bat = _kpi_frame("B", 7, rng, rng.normal(size=7), lambda c, r, j: r.normal(1, .1, len(c)))
    flags = pd.concat([_flags_from(ref, ["ordinary"] * 3 + ["grey_pore"] * 5), _flags_from(bat)])
    out = acq.stratified_comparison(ref, bat, PRIMARY_KPIS, flags, statistic="hl_shift", n_boot=50)
    assert out["compare"] is None and out["energy"] is None
    assert out["n_ref_kept"] == 3 and out["n_batch_kept"] == 7
    assert "not run" in out["reason"] and len(out["dropped_sites"]) == 5
    # with enough sites it runs and only the kept sites enter
    flags2 = pd.concat([_flags_from(ref, ["ordinary"] * 5 + ["grey_pore"] * 3), _flags_from(bat)])
    out2 = acq.stratified_comparison(ref, bat, PRIMARY_KPIS, flags2, statistic="hl_shift", n_boot=50, n_mc_energy=200)
    assert out2["reason"] is None and out2["energy"]["n_ref"] == 5 and out2["energy"]["n_batch"] == 7
    assert (out2["compare"].n_ref_usable == 5).all()


# --------------------------------------------------------------------------------------------- adjusted view
def test_adjusted_attenuates_only_when_covariate_explains_shift():
    rng = np.random.default_rng(2)
    n_r, n_b = 17, 7
    # covariate shifted in the batch, KPIs are 2*cov + small noise: the covariate fully explains the shift
    c_r, c_b = rng.normal(0, 1, n_r), rng.normal(3, 1, n_b)
    gen = lambda c, r, j: 2.0 * c + r.normal(0, 0.3, len(c))
    ref, bat = _kpi_frame("R", n_r, rng, c_r, gen), _kpi_frame("B", n_b, rng, c_b, gen)
    flags = pd.concat([_flags_from(ref), _flags_from(bat)])
    e0 = acq._energy(ref, bat, PRIMARY_KPIS, None, None, 200, 0)
    adj = acq.adjusted_comparison(ref, bat, PRIMARY_KPIS, flags, covariates=["cov"], n_mc=200, n_boot=50)
    e1 = adj["energy_adjusted"]
    assert e0["statistic"] > 5 * e1["statistic"] >= 0
    assert (adj["covariate_fit"].r2_ref > 0.9).all()
    assert (adj["covariate_fit"].n_ref_fit == n_r).all()
    # a covariate unrelated to the shift leaves the statistic within 10 %
    c_r2, c_b2 = rng.normal(0, 1, n_r), rng.normal(0, 1, n_b)
    gen2 = lambda c, r, j: r.normal(0, 1, len(c))
    ref2, bat2 = _kpi_frame("R", n_r, rng, c_r2, gen2), _kpi_frame("B", n_b, rng, c_b2, gen2)
    for k in PRIMARY_KPIS:
        bat2[k] += 2.0
    flags2 = pd.concat([_flags_from(ref2), _flags_from(bat2)])
    e2 = acq._energy(ref2, bat2, PRIMARY_KPIS, None, None, 200, 0)
    adj2 = acq.adjusted_comparison(ref2, bat2, PRIMARY_KPIS, flags2, covariates=["cov"], n_mc=200, n_boot=50)
    assert abs(adj2["energy_adjusted"]["statistic"] / e2["statistic"] - 1) < 0.10
    cmp_ = adj2["compare_adjusted"]
    assert {"p_perm", "p_perm_fixed_residuals", "p_holm", "p_reported"} <= set(cmp_.columns)
    assert (cmp_.n_perm == 200).all() and cmp_.p_method.str.contains("refit").all()
    assert (cmp_.loc[cmp_.is_primary, "p_holm"] <= 1).all()


def test_adjusted_energy_null_is_uniform_with_in_loop_refit():
    """Under the null (same distribution both sides, KPI = covariate + noise) the Monte Carlo p of the adjusted
    energy test must be ~ uniform. This holds only if the regression is re-fitted on the permuted reference rows
    inside every permutation (checklist C09)."""
    rng = np.random.default_rng(3)
    n_r, n_b, n_sim = 17, 7, 50
    p_refit = []
    for s in range(n_sim):
        c = rng.normal(0, 1, n_r + n_b)
        Y = c[:, None] + rng.normal(0, 1, (n_r + n_b, 2))
        out = acq.adjusted_energy_permutation(Y[:n_r], Y[n_r:], c[:n_r, None], c[n_r:, None], n_mc=199, seed=s)
        assert out["n_perm"] == 199 and "refit" in out["method"]
        p_refit.append(out["p"])
    ks = sps.kstest(p_refit, "uniform")
    assert ks.pvalue > 0.01, f"adjusted energy null not uniform: KS p = {ks.pvalue:.3f}, mean p = {np.mean(p_refit):.2f}"


def test_residualise_exact_fit_and_imputation():
    rng = np.random.default_rng(4)
    ref = _kpi_frame("R", 10, rng, rng.normal(size=10), lambda c, r, j: 3 * c + j)
    bat = _kpi_frame("B", 5, rng, rng.normal(size=5), lambda c, r, j: 3 * c + j + 1)
    bat.loc[0, "cov"] = np.nan
    rr, bb, fit = acq.residualise(ref, bat, PRIMARY_KPIS, ["cov"])
    assert np.allclose(fit.r2_ref, 1.0) and (fit.n_imputed == 1).all()
    assert np.allclose(rr[PRIMARY_KPIS].to_numpy(), 0, atol=1e-8)
    assert bb[PRIMARY_KPIS].notna().all().all()
    assert np.allclose(bb.loc[1:, PRIMARY_KPIS].to_numpy(), 1.0, atol=1e-8)     # the shift survives; the imputed row does not


# -------------------------------------------------------------------------------------- three-channel agreement
def test_three_channel_agreement_patterns():
    rng = np.random.default_rng(5)
    n = 15
    names = [f"s{i}" for i in range(n)]
    # bounded baseline: a shuffled even grid has MAD = range/4, so the largest baseline |robust z| is 1/0.74 = 1.35 < 2
    u = lambda lo, hi: lo + (hi - lo) * rng.permutation(np.linspace(0, 1, n))
    sites = pd.DataFrame(dict(batch="B", site=names, corr_len_px=u(19, 21), etd_grad_energy=u(.95, 1.05), inlens_grad_energy=u(.95, 1.05)))
    p50 = dict(BSE=u(54, 56), ETD=u(79, 81), Inlens=u(99, 101))
    # s12: intensity-only (BSE up, Inlens down); s13: texture across two channels; s14: both; s11: one texture channel only
    p50["BSE"][12] += 10; p50["Inlens"][12] -= 15
    sites.loc[13, "etd_grad_energy"] -= 0.5; sites.loc[13, "corr_len_px"] += 8
    p50["ETD"][14] += 10; sites.loc[14, "etd_grad_energy"] += 0.5; sites.loc[14, "inlens_grad_energy"] += 0.5
    sites.loc[11, "etd_grad_energy"] -= 0.5
    images = pd.DataFrame([dict(batch="B", site=s, det=d, p50=p50[{"SE": "ETD"}.get(d, d)][i])
                           for i, s in enumerate(names) for d in ("BSE", "SE", "Inlens")])   # SE label == ETD detector
    Z = acq.three_channel_agreement(sites, images).set_index("site")
    assert Z.loc["s12", "pattern"] == "intensity-only shift" and Z.loc["s12", "intensity_disagreement"] > 2
    assert Z.loc["s13", "pattern"] == "texture shift across channels" and Z.loc["s13", "texture_channels_shifted"] == 2
    assert Z.loc["s14", "pattern"] == "mixed"
    assert Z.loc["s11", "pattern"] == "none" and Z.loc["s11", "texture_channels_shifted"] == 1
    assert (Z.loc[[f"s{i}" for i in range(11)], "pattern"] == "none").all()
    assert {"z_BSE_p50", "z_ETD_p50", "z_Inlens_p50", "z_corr_len_px", "z_etd_grad_energy", "z_inlens_grad_energy"} <= set(Z.columns)
    # reference-relative scaling keeps the same labels here (reference = all sites)
    Z2 = acq.three_channel_agreement(sites, images, reference_batch="B")
    assert (Z2.pattern.to_numpy() == Z.pattern.to_numpy()).all()


# ------------------------------------------------------------------------------------------------- smoke tests
@pytest.mark.skipif(not os.path.exists(os.path.join(CACHE, "site_features.csv")), reason="no analysis cache")
def test_real_cache_flags_match_known_groups():
    sites, images = acq.load_site_tables(CACHE)
    f = acq.derive_flags(sites, images)
    assert len(f) == 31 and f.site.is_unique
    g = f.set_index("site")
    assert all(g.loc[s, "acquisition_group"] == "grey_pore" and g.loc[s, "grey_pore_source"] == "data+list" for s in GREY_PORE_SITES)
    assert all(g.loc[s, "acquisition_group"] == "low_contrast" for s in LOW_CONTRAST_SITES)
    assert all(g.loc[s, "acquisition_group"] == "cracked" for s in CRACKED_SITES)
    # the data rule alone reproduces the grey-pore list on Batches 1–3
    assert set(g.index[g.raised_black_level]) == set(GREY_PORE_SITES)
    assert f.acquisition_group.value_counts().to_dict() == {"ordinary": 22, "grey_pore": 4, "cracked": 3, "low_contrast": 2}


@pytest.mark.skipif(not os.path.isdir(os.path.join(DATASET, "Batch_3")) or not os.path.exists(os.path.join(CACHE, "site_features.csv")),
                    reason="no raw images")
def test_threshold_band_real_site():
    sites = pd.read_csv(os.path.join(CACHE, "site_features.csv")).set_index("site")
    site = "cfe5vt7s"
    r = sites.loc[site]
    tb = acq.threshold_band(os.path.join(DATASET, "Batch_3"), site, r.th_lo, r.th_hi, delta=5)
    for k in ("pore_frac_nominal", "pore_frac_lo_minus", "pore_frac_lo_plus", "bright_frac_nominal", "bright_frac_hi_minus",
              "bright_frac_hi_plus", "pore_frac_band_rel", "bright_frac_band_rel"):
        assert 0 < tb[k] < 1
    assert tb["pore_frac_lo_minus"] < tb["pore_frac_nominal"] < tb["pore_frac_lo_plus"]
    assert tb["bright_frac_hi_plus"] < tb["bright_frac_nominal"] < tb["bright_frac_hi_minus"]
    assert abs(tb["pore_frac_nominal"] - r.pore_frac) < 1e-6 and abs(tb["bright_frac_nominal"] - r.bright_frac) < 1e-6
